import { IMealDetails } from './SearchResults';

interface IMealDetailsModalProps {
  mealDetails: IMealDetails | null;
  handleCloseModal: () => void;
}

const MealDetailsModal = ({
  mealDetails,
  handleCloseModal,
}: IMealDetailsModalProps) => {
  return (
    <>
      <div
        id='details-modal'
        tabIndex={-1}
        className='fixed top-0 left-0 right-0 z-50 flex h-full w-full justify-center overflow-y-auto overflow-x-hidden p-4 md:inset-0'
        role='dialog'
      >
        <div className='relative h-full w-full max-w-4xl md:h-auto'>
          {/* Modal content autogenerated based on selected meal */}
          <div className='relative mx-auto max-w-4xl rounded-lg bg-gray-700'>
            {/* Modal header */}
            <div className='flex items-center justify-between rounded-t border-b border-gray-600 p-5'>
              <h3
                className='text-clamp-12-17 font-medium capitalize text-white'
                id='modal-recipe-title'
              >
                {mealDetails?.strMeal} 🥘
              </h3>
              <button
                type='button'
                id='close-btn'
                className='ml-auto inline-flex items-center rounded-lg bg-transparent p-1.5 text-sm text-gray-400 hover:bg-gray-600 hover:text-white'
                onClick={handleCloseModal}
              >
                <svg
                  aria-hidden='true'
                  className='h-5 w-5'
                  fill='currentColor'
                  viewBox='0 0 20 20'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <path
                    fillRule='evenodd'
                    d='M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z'
                    clipRule='evenodd'
                  />
                </svg>
                <span className='sr-only'>Close modal</span>
              </button>
            </div>
            {/* Modal body */}
            <div className='space-y-6 p-6'>
              <div className='flex flex-wrap items-center justify-between gap-4'>
                <h3 className='text-clamp-12-17'>Recipe Preparation 📝🍳</h3>
                <div className='rounded border px-4 py-0.5 md:px-8'>
                  <span
                    className='text-center text-sm font-semibold text-white'
                    id='modal-recipe-category'
                  >
                    🍽️ {mealDetails?.strCategory}
                  </span>
                </div>
              </div>
              <p
                className='text-sm leading-relaxed text-gray-400 md:text-base'
                id='modal-preparation-instructions'
              >
                {mealDetails?.strInstructions
                  .split('\n')
                  .map((instruction, index) => (
                    <>
                      <p key={index} className='mb-4'>
                        {instruction}
                      </p>
                    </>
                  ))}
              </p>
              <p className='text-sm leading-relaxed text-gray-400 visited:text-gray-400 hover:text-white active:text-gray-500 md:text-base'>
                <a
                  href={mealDetails?.strSource}
                  target='_blank'
                  rel='noopener noreferrer'
                >
                  Click here to view source...
                </a>
              </p>
            </div>
            {/* Modal footer */}
            <div className='flex flex-col items-center gap-8 space-x-2 rounded-b border-t border-gray-600 p-6'>
              <h3 className='text-clamp-12-17 text-center'>
                Recipe Tutorial Video 🎥👨‍🍳
              </h3>
              <div className='h-full w-full'>
                <iframe
                  id='modal-yt-video'
                  className='video-embed mx-auto'
                  src={`https://www.youtube.com/embed/${
                    mealDetails?.strYoutube.split('?v=')[1]
                  }`}
                  title='Recipe Tutorial Video'
                  allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share'
                  allowFullScreen
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className='overlay fixed inset-0 z-40 h-full w-full bg-slate-900 opacity-90'
        id='overlay'
      />
    </>
  );
};

export default MealDetailsModal;
